import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { isSignedIn, user, isLoaded } = useUser();
  const { data } = api.post.getAll.useQuery();
  console.log("data:", data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#16222A] to-[#3A6073]">
        {isLoaded ? "Yep" : "Nope"}
        {isSignedIn ? <SignOutButton /> : <SignInButton />}
      </main>
    </>
  );
};

export default Home;
